<Project Sdk="Microsoft.NET.Sdk">

    <PropertyGroup>
        <OutputType>Exe</OutputType>
        <TargetFramework>net10.0</TargetFramework>
        <RootNamespace>Morphir.IR.Pipeline.Plugins.Tests</RootNamespace>
        <GenerateDocumentationFile>false</GenerateDocumentationFile>
        <GenerateProgramFile>false</GenerateProgramFile>
        <IsPackable>false</IsPackable>
    </PropertyGroup>

    <ItemGroup>
        <PackageReference Include="Expecto" />
        <PackageReference Include="FSharp.Core" />
        <PackageReference Include="Microsoft.NET.Test.Sdk" />
        <PackageReference Include="YoloDev.Expecto.TestSdk" />
        <PackageReference Include="coverlet.collector">
            <IncludeAssets>runtime; build; native; contentfiles; analyzers; buildtransitive</IncludeAssets>
            <PrivateAssets>all</PrivateAssets>
        </PackageReference>
        <PackageReference Include="altcover" />
    </ItemGroup>

    <ItemGroup>
        <ProjectReference Include="..\..\src\Morphir.IR.Pipeline.Plugins\Morphir.IR.Pipeline.Plugins.fsproj" />
        <ProjectReference Include="..\..\src\Morphir.IR.Pipeline\Morphir.IR.Pipeline.fsproj" />
        <ProjectReference Include="..\..\src\Morphir.Models\Morphir.Models.fsproj" />
    </ItemGroup>

    <ItemGroup>
        <Compile Include="TypeValidatorTests.fs" />
        <Compile Include="OptimizerTests.fs" />
        <Compile Include="PrettyPrinterTests.fs" />
        <Compile Include="Program.fs" />
    </ItemGroup>

</Project>
