namespace Morphir.Internal.CodeGeneration.Core

/// Common code generation patterns and utilities
module CodeGenHelpers =
    
    open System
    
    /// Configuration for code generation
    type GeneratorConfig = {
        Namespace: string option
        AdditionalOptions: Map<string, string>
    }
    
    /// Create a default generator configuration
    let defaultConfig = {
        Namespace = None
        AdditionalOptions = Map.empty
    }
    
    /// Get the target namespace for generated code
    let getTargetNamespace (config: GeneratorConfig) (sourceNamespace: string) : string =
        match config.Namespace with
        | Some ns -> ns
        | None -> $"{sourceNamespace}.Generated"
    
    /// Convert a string to camelCase
    let toCamelCase (str: string) : string =
        if String.IsNullOrEmpty(str) then str
        else
            let first = Char.ToLowerInvariant(str.[0])
            if str.Length = 1 then string first
            else string first + str.Substring(1)
    
    /// Convert a string to PascalCase
    let toPascalCase (str: string) : string =
        if String.IsNullOrEmpty(str) then str
        else
            let first = Char.ToUpperInvariant(str.[0])
            if str.Length = 1 then string first
            else string first + str.Substring(1)
    
    /// Apply a naming policy to a property name
    let applyNamingPolicy (policy: string) (name: string) : string =
        match policy.ToLowerInvariant() with
        | "camelcase" -> toCamelCase name
        | "pascalcase" -> toPascalCase name
        | _ -> name
    
    /// Generate a comment for generated code
    let generatedCodeComment = 
        "// This code was generated by Morphir.Internal.CodeGeneration"
