<Project Sdk="Microsoft.NET.Sdk">

    <PropertyGroup>
        <TargetFramework>net10.0</TargetFramework>
        <ImplicitUsings>enable</ImplicitUsings>
        <Nullable>enable</Nullable>
        <OutputType>Exe</OutputType>
        <IsPackable>false</IsPackable>

        <!-- To enable Microsoft.Testing.Platform, uncomment the following line. -->
        <UseMicrosoftTestingPlatformRunner>true</UseMicrosoftTestingPlatformRunner>
        <TestingPlatformDotnetTestSupport>true</TestingPlatformDotnetTestSupport>
        <RootNamespace>Morphir.Dotnet</RootNamespace> 
        <!-- Note: to use Microsoft.Testing.Platform correctly with dotnet test: -->
        <!-- 1. You must add dotnet.config specifying the test runner to be Microsoft.Testing.Platform -->
        <!-- 2. You must use .NET 10 SDK or later -->
        <!-- For more information, see https://aka.ms/dotnet-test/mtp and https://xunit.net/docs/getting-started/v3/microsoft-testing-platform -->
        <!-- To enable code coverage with Microsoft.Testing.Platform, add a package reference to Microsoft.Testing.Extensions.CodeCoverage -->
        <!-- https://learn.microsoft.comdotnet/core/testing/microsoft-testing-platform-extensions-code-coverage -->
    </PropertyGroup>

    <ItemGroup>
        <PackageReference Include="FluentAssertions" />
        <PackageReference Include="Microsoft.NET.Test.Sdk" />
        <PackageReference Include="Microsoft.Testing.Extensions.CodeCoverage" />
        <PackageReference Include="xunit.v3" />
        <PackageReference Include="xunit.runner.visualstudio" />
    </ItemGroup>

    <ItemGroup>
        <Content Include="xunit.runner.json" CopyToOutputDirectory="PreserveNewest" />
    </ItemGroup>

    <ItemGroup>
        <Using Include="Xunit" />
        <Using Include="FluentAssertions" />
    </ItemGroup>

    <ItemGroup>
      <Folder Include="IR\Classic\" />
    </ItemGroup>

    <ItemGroup>
      <ProjectReference Include="..\..\src\Morphir.DotNet.Core\Morphir.DotNet.Core.csproj" />
    </ItemGroup>

</Project>
