<Project Sdk="Microsoft.NET.Sdk">

    <PropertyGroup>
        <OutputType>Library</OutputType>
        <GenerateProgramFile>false</GenerateProgramFile>
        <TargetFramework>net10.0</TargetFramework>
        <GenerateDocumentationFile>false</GenerateDocumentationFile>
        <RootNamespace>Morphir</RootNamespace>
    </PropertyGroup>

    <ItemGroup>
        <PackageReference Include="FSharp.Core" />
        <PackageReference Include="Microsoft.NET.Test.Sdk" />
        <PackageReference Include="Expecto" />
        <PackageReference Include="Expecto.FsCheck" />
        <PackageReference Include="Verify.Expecto" />
    </ItemGroup>

    <ItemGroup>
        <ProjectReference Include="..\..\src\Morphir.Models\Morphir.Models.fsproj" />
        <ProjectReference Include="..\..\src\Morphir.Testing\Morphir.Testing.fsproj" />
    </ItemGroup>

    <ItemGroup>
        <Compile Include="IR/NameTests.fs" />
        <Compile Include="IR/PathTests.fs" />
        <Compile Include="IR/PackageNameTests.fs" />
        <Compile Include="IR/ModulePathTests.fs" />
        <Compile Include="IR/FQNameTests.fs" />
        <Compile Include="IR/Classic/AccessControlledTests.fs" />
        <Compile Include="IR/Classic/TypeTests.fs" />
        <Compile Include="IR/Classic/LiteralTests.fs" />
        <Compile Include="IR/Classic/PatternTests.fs" />
        <Compile Include="IR/Classic/ValueTests.fs" />
        <Compile Include="IR/Classic/DocumentedTests.fs" />
        <Compile Include="IR/Classic/ModuleTests.fs" />
        <Compile Include="IR/Classic/PackageTests.fs" />
        <Compile Include="Program.fs" />
    </ItemGroup>

</Project>

