<Project Sdk="Microsoft.NET.Sdk">

    <PropertyGroup>
        <TargetFramework>net10.0</TargetFramework>
        <RootNamespace>Morphir.IR.Pipeline</RootNamespace>
        <GenerateDocumentationFile>true</GenerateDocumentationFile>
    </PropertyGroup>

    <ItemGroup>
        <PackageReference Include="FSharp.Core" />
    </ItemGroup>

    <ItemGroup>
        <Compile Include="File.fs" />
        <Compile Include="FileTree.fs" />
        <Compile Include="Processor.fs" />
        <Compile Include="PipelineBuilder.fs" />
    </ItemGroup>

</Project>
