<Project Sdk="Microsoft.NET.Sdk">

    <PropertyGroup>
        <TargetFramework>net10.0</TargetFramework>
        <RootNamespace>Morphir.Testing</RootNamespace>
        <GenerateDocumentationFile>false</GenerateDocumentationFile>
    </PropertyGroup>

    <ItemGroup>
        <PackageReference Include="Expecto" />
        <PackageReference Include="FSharp.Core" />
    </ItemGroup>

    <ItemGroup>
        <Compile Include="Assertions.fs" />
    </ItemGroup>

</Project>

