<Project Sdk="Microsoft.NET.Sdk">

    <PropertyGroup>
        <TargetFramework>net10.0</TargetFramework>
        <ImplicitUsings>enable</ImplicitUsings>
        <Nullable>enable</Nullable>
        <OutputType>Exe</OutputType>
        <IsPackable>false</IsPackable>
        <RootNamespace>Morphir</RootNamespace>

    </PropertyGroup>

    <ItemGroup>
        <PackageReference Include="Microsoft.Testing.Extensions.CodeCoverage" />
        <PackageReference Include="TUnit" />
        <PackageReference Include="Verify.TUnit" />
    </ItemGroup>
    

    <ItemGroup>
      <ProjectReference Include="..\..\src\Morphir.Core\Morphir.Core.csproj" />
    </ItemGroup>

</Project>
