<Project Sdk="Microsoft.NET.Sdk">

    <PropertyGroup>
        <TargetFramework>net10.0</TargetFramework>
        <ImplicitUsings>enable</ImplicitUsings>
        <Nullable>enable</Nullable>
        <OutputType>Exe</OutputType>
        <IsPackable>false</IsPackable>
        <RootNamespace>Morphir</RootNamespace>

    </PropertyGroup>

    <ItemGroup>
        <PackageReference Include="coverlet.collector" />
        <PackageReference Include="Json.More.Net" />
        <PackageReference Include="Reqnroll" />
        <PackageReference Include="Reqnroll.TUnit" />
        <PackageReference Include="Shouldly" />
        <PackageReference Include="Shouldly.Json" />
        <PackageReference Include="TUnit" />
        <PackageReference Include="Verify.TUnit" />
    </ItemGroup>
    

    <ItemGroup>
      <ProjectReference Include="..\..\src\Morphir.Core\Morphir.Core.csproj" />
    </ItemGroup>
    
    <ItemGroup>
        <Content Include="**/*.feature"/>
    </ItemGroup>
    
    <ItemGroup>
        <Using Include="LanguageExt" />
        <Using Include="LanguageExt.Prelude" Static="True" />
        <Using Include="LanguageExt.Seq" Static="True" />
        <Using Include="Reqnroll" />
    </ItemGroup>
    
    <ItemGroup>
        <!-- hiding .gitkeep files in Visual Studio; they are only needed to ensure the existence of the empty folders in git -->
        <None Update="**/.gitkeep" Visible="false" />
    </ItemGroup>
</Project>
