// Auto-Generated by FAKE; do not edit
// <auto-generated/>
using System.Reflection;

[assembly: AssemblyTitle("Morphir.SDK.Core.CSharp.Tests")]
[assembly: AssemblyProduct("Morphir")]
[assembly: AssemblyVersion("0.1.0")]
[assembly: AssemblyMetadata("ReleaseDate","2017-03-17T00:00:00.0000000")]
[assembly: AssemblyFileVersion("0.1.0")]
[assembly: AssemblyInformationalVersion("0.1.0")]
[assembly: AssemblyMetadata("ReleaseChannel","release")]
[assembly: AssemblyMetadata("GitHash","d3b04c2b54e803b3cde238e77c2d935702df015f")]
namespace System {
    internal static class AssemblyVersionInformation {
        internal const System.String AssemblyTitle = "Morphir.SDK.Core.CSharp.Tests";
        internal const System.String AssemblyProduct = "Morphir";
        internal const System.String AssemblyVersion = "0.1.0";
        internal const System.String AssemblyMetadata_ReleaseDate = "2017-03-17T00:00:00.0000000";
        internal const System.String AssemblyFileVersion = "0.1.0";
        internal const System.String AssemblyInformationalVersion = "0.1.0";
        internal const System.String AssemblyMetadata_ReleaseChannel = "release";
        internal const System.String AssemblyMetadata_GitHash = "d3b04c2b54e803b3cde238e77c2d935702df015f";
    }
}
