// Auto-Generated by FAKE; do not edit
namespace System
open System.Reflection

[<assembly: AssemblyTitleAttribute("Morphir.SDK.Core.Tests")>]
[<assembly: AssemblyProductAttribute("Morphir")>]
[<assembly: AssemblyVersionAttribute("0.0.1")>]
[<assembly: AssemblyMetadataAttribute("ReleaseDate","2023-04-14T00:00:00.0000000-04:00")>]
[<assembly: AssemblyFileVersionAttribute("0.0.1")>]
[<assembly: AssemblyInformationalVersionAttribute("0.0.1")>]
[<assembly: AssemblyMetadataAttribute("ReleaseChannel","alpha")>]
[<assembly: AssemblyMetadataAttribute("GitHash","76beb12451e41abcfa58d69060dab00f37336966")>]
do ()

module internal AssemblyVersionInformation =
    let [<Literal>] AssemblyTitle = "Morphir.SDK.Core.Tests"
    let [<Literal>] AssemblyProduct = "Morphir"
    let [<Literal>] AssemblyVersion = "0.0.1"
    let [<Literal>] AssemblyMetadata_ReleaseDate = "2023-04-14T00:00:00.0000000-04:00"
    let [<Literal>] AssemblyFileVersion = "0.0.1"
    let [<Literal>] AssemblyInformationalVersion = "0.0.1"
    let [<Literal>] AssemblyMetadata_ReleaseChannel = "alpha"
    let [<Literal>] AssemblyMetadata_GitHash = "76beb12451e41abcfa58d69060dab00f37336966"
