// Auto-Generated by FAKE; do not edit
// <auto-generated/>
using System.Reflection;

[assembly: AssemblyTitle("Morphir.IR.CSharp.Tests")]
[assembly: AssemblyProduct("Morphir")]
[assembly: AssemblyVersion("0.0.1")]
[assembly: AssemblyMetadata("ReleaseDate","2023-04-14T00:00:00.0000000-04:00")]
[assembly: AssemblyFileVersion("0.0.1")]
[assembly: AssemblyInformationalVersion("0.0.1")]
[assembly: AssemblyMetadata("ReleaseChannel","alpha")]
[assembly: AssemblyMetadata("GitHash","282c5e3a534fc4f27bb97d4d70c580e27661c7bc")]
namespace System {
    internal static class AssemblyVersionInformation {
        internal const System.String AssemblyTitle = "Morphir.IR.CSharp.Tests";
        internal const System.String AssemblyProduct = "Morphir";
        internal const System.String AssemblyVersion = "0.0.1";
        internal const System.String AssemblyMetadata_ReleaseDate = "2023-04-14T00:00:00.0000000-04:00";
        internal const System.String AssemblyFileVersion = "0.0.1";
        internal const System.String AssemblyInformationalVersion = "0.0.1";
        internal const System.String AssemblyMetadata_ReleaseChannel = "alpha";
        internal const System.String AssemblyMetadata_GitHash = "282c5e3a534fc4f27bb97d4d70c580e27661c7bc";
    }
}
