// Auto-Generated by FAKE; do not edit
// <auto-generated/>
using System.Reflection;

[assembly: AssemblyTitle("Morphir.IR.CSharp.Tests")]
[assembly: AssemblyProduct("Morphir")]
[assembly: AssemblyVersion("0.0.1")]
[assembly: AssemblyMetadata("ReleaseDate","2023-03-10T00:00:00.0000000-05:00")]
[assembly: AssemblyFileVersion("0.0.1")]
[assembly: AssemblyInformationalVersion("0.0.1")]
[assembly: AssemblyMetadata("ReleaseChannel","alpha")]
[assembly: AssemblyMetadata("GitHash","9bbd101a3df88249c74a2fb456aeef01b53de12e")]
namespace System {
    internal static class AssemblyVersionInformation {
        internal const System.String AssemblyTitle = "Morphir.IR.CSharp.Tests";
        internal const System.String AssemblyProduct = "Morphir";
        internal const System.String AssemblyVersion = "0.0.1";
        internal const System.String AssemblyMetadata_ReleaseDate = "2023-03-10T00:00:00.0000000-05:00";
        internal const System.String AssemblyFileVersion = "0.0.1";
        internal const System.String AssemblyInformationalVersion = "0.0.1";
        internal const System.String AssemblyMetadata_ReleaseChannel = "alpha";
        internal const System.String AssemblyMetadata_GitHash = "9bbd101a3df88249c74a2fb456aeef01b53de12e";
    }
}
