// Auto-Generated by FAKE; do not edit
namespace System
open System.Reflection

[<assembly: AssemblyTitleAttribute("Morphir.SDK.Testing")>]
[<assembly: AssemblyProductAttribute("Morphir")>]
[<assembly: AssemblyVersionAttribute("0.0.1")>]
[<assembly: AssemblyMetadataAttribute("ReleaseDate","2023-04-20T00:00:00.0000000+00:00")>]
[<assembly: AssemblyFileVersionAttribute("0.0.1")>]
[<assembly: AssemblyInformationalVersionAttribute("0.0.1")>]
[<assembly: AssemblyMetadataAttribute("ReleaseChannel","alpha")>]
[<assembly: AssemblyMetadataAttribute("GitHash","8ed4ca356ac30d12289e8c413c34d734c48a4813")>]
do ()

module internal AssemblyVersionInformation =
    let [<Literal>] AssemblyTitle = "Morphir.SDK.Testing"
    let [<Literal>] AssemblyProduct = "Morphir"
    let [<Literal>] AssemblyVersion = "0.0.1"
    let [<Literal>] AssemblyMetadata_ReleaseDate = "2023-04-20T00:00:00.0000000+00:00"
    let [<Literal>] AssemblyFileVersion = "0.0.1"
    let [<Literal>] AssemblyInformationalVersion = "0.0.1"
    let [<Literal>] AssemblyMetadata_ReleaseChannel = "alpha"
    let [<Literal>] AssemblyMetadata_GitHash = "8ed4ca356ac30d12289e8c413c34d734c48a4813"
