// <auto-generated/>
// This file conditionally configures Wolverine TypeLoadMode based on build configuration
// For Release builds with EnableWolverineCodeGeneration=true, use Static mode
// For Debug builds or when code generation is disabled, use Auto mode (default)
#if ENABLE_WOLVERINE_CODE_GENERATION
using System.Diagnostics.CodeAnalysis;
using System.Reflection;

namespace Morphir.Tooling;

public static partial class Program
{
    [RequiresUnreferencedCode("Uses reflection to set TypeLoadMode. Only used in Release builds with pre-generated code.")]
    [RequiresDynamicCode("Uses reflection to set TypeLoadMode.")]
    [UnconditionalSuppressMessage("Trimming", "IL2026", Justification = "Uses reflection to set TypeLoadMode but only runs when pre-generated code exists")]
    private static void ConfigureWolverineCodeGeneration(Wolverine.WolverineOptions opts)
    {
        // Use Static mode for Release builds with pre-generated code
        // Static mode requires pre-generated code and will not fall back to dynamic generation
        // This is necessary for trimmed executables where dynamic generation doesn't work
        // Use reflection to avoid type ambiguity between JasperFx.CodeGeneration and JasperFx
        var codeGen = opts.CodeGeneration;
        var prop = codeGen.GetType().GetProperty("TypeLoadMode", BindingFlags.Public | BindingFlags.Instance);
        if (prop != null && prop.PropertyType.IsEnum)
        {
            // Static enum value is 2
            var staticValue = System.Enum.ToObject(prop.PropertyType, 2);
            prop.SetValue(codeGen, staticValue);
        }
    }
}
#endif

