// Auto-Generated by FAKE; do not edit
namespace System
open System.Reflection

[<assembly: AssemblyTitleAttribute("Morphir.SDK.Core")>]
[<assembly: AssemblyProductAttribute("Morphir")>]
[<assembly: AssemblyVersionAttribute("0.0.1")>]
[<assembly: AssemblyMetadataAttribute("ReleaseDate","2023-04-20T00:00:00.0000000+00:00")>]
[<assembly: AssemblyFileVersionAttribute("0.0.1")>]
[<assembly: AssemblyInformationalVersionAttribute("0.0.1")>]
[<assembly: AssemblyMetadataAttribute("ReleaseChannel","alpha")>]
[<assembly: AssemblyMetadataAttribute("GitHash","99a68f79ab1e7f1b9b3f37fc377114155f4c7e50")>]
do ()

module internal AssemblyVersionInformation =
    let [<Literal>] AssemblyTitle = "Morphir.SDK.Core"
    let [<Literal>] AssemblyProduct = "Morphir"
    let [<Literal>] AssemblyVersion = "0.0.1"
    let [<Literal>] AssemblyMetadata_ReleaseDate = "2023-04-20T00:00:00.0000000+00:00"
    let [<Literal>] AssemblyFileVersion = "0.0.1"
    let [<Literal>] AssemblyInformationalVersion = "0.0.1"
    let [<Literal>] AssemblyMetadata_ReleaseChannel = "alpha"
    let [<Literal>] AssemblyMetadata_GitHash = "99a68f79ab1e7f1b9b3f37fc377114155f4c7e50"
