name: CI

on:
    pull_request:
    push:
        branches: ['main']
    release:
        types:
            - published

jobs:
    build:
        strategy:
            matrix:
                os: [ubuntu-latest, windows-latest, macOS-latest]
        runs-on: ${{ matrix.os }}
        
        steps:
            - uses: actions/checkout@v2
            - name: Setup .NET Core SDK
              uses: actions/setup-dotnet@v2
              with:
                  dotnet-version: '7.0.x'
            # Not specifying a version will attempt to install via global.json
            - name: Use .NET Core global.json
              uses: actions/setup-dotnet@v2

            - name: Build
              if: runner.os != 'Windows'
              run: |
                  chmod +x ./build.sh
                  ./build.sh
              env:
                  CI: true
            - name: Build
              if: runner.os == 'Windows'
              run: ./build.cmd
              env:
                  CI: true
