name: CI

on:
    pull_request:
    push:
        branches: ['main']
    release:
        types:
            - published
    workflow_call:

jobs:
    build:
        strategy:
            matrix:
                os: [ubuntu-latest, windows-latest, macOS-latest]
        runs-on: ${{ matrix.os }}
        
        steps:
            - uses: actions/checkout@v2
            - name: Setup .NET Core SDK
              uses: actions/setup-dotnet@v2
              with:
                  dotnet-version: '7.0.x'
            # Not specifying a version will attempt to install via global.json
            - name: Use .NET Core global.json
              uses: actions/setup-dotnet@v2
            - uses: actions/cache@v3
              with:
                  path: ~/.nuget/packages
                  # Look to see if there is a cache hit for the corresponding requirements file
                  key: ${{ runner.os }}-nuget-${{ hashFiles('**/packages.lock.json') }}
                  restore-keys: |
                      ${{ runner.os }}-nuget
            - name: Build
              if: runner.os != 'Windows'
              run: |
                  chmod +x ./build.sh
                  ./build.sh PackItUp
              env:
                  CI: true
            - name: Build
              if: runner.os == 'Windows'
              run: ./build.cmd PackItUp
              env:
                  CI: true
            - name: Upload Artifacts
              uses: actions/upload-artifact@v2
              with:
                name: dist
                path: ./dist
