name: Release

on:
  workflow_dispatch:
      inputs:
            version:
                description: 'Version'
                required: true
                default: 'v1.0.0'
  branch:
      - 'main'
  push:
    tags: 
      - 'v[0-9]+.[0-9]+.[0-9]+*'
    
jobs:
  build:
    uses: ./.github/workflows/build.yml

  nuget-push:
    runs-on: ubuntu-latest
    needs: build
    steps:

      - name: Download artifacts
        uses: actions/download-artifact@v2
        with:
          name: packages
          path: ./packages
      
      - name: Publish
        if: runner.os != 'Windows'
        run: |
            chmod +x ./build.sh
            ./build.sh Release
        env:
            GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
            CI: true
      - name: Publish
        if: runner.os == 'Windows'
        run: ./build.cmd Release
        env:
            GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
            CI: true
