name: Release

on:
  push:
    tags: 
      - 'v0.**'
      - 'v1.**'
      - 'v2.**'
    
env:
    GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
    
jobs:
  build:
    uses: ./.github/workflows/build.yml

  nuget-push:
    runs-on: ubuntu-latest
    needs: build
    steps:

      - name: Download artifacts
        uses: actions/download-artifact@v2
        with:
          name: packages
          path: ./packages
      
      - name: Publish
        if: runner.os != 'Windows'
        run: |
            chmod +x ./build.sh
            ./build.sh Release
        env:
            CI: true
      - name: Publish
        if: runner.os == 'Windows'
        run: ./build.cmd Release
        env:
            CI: true
